
set mouse=a

"set cursorcolumn
set cursorline
set hls
syntax on
set smartindent  "自动缩进
set nu
set incsearch  " 逐字符高亮
set cindent   
set expandtab
set tabstop=4
set shiftwidth=4 "设置自动缩进长度为4格
set autoindent 
set showmatch "显示括号匹配 





let g:miniBufExplMapWindowNavVim = 1   
let g:miniBufExplMapWindowNavArrows = 1   
let g:miniBufExplMapCTabSwitchBufs = 1   
let g:miniBufExplModSelTarget = 1  
let g:miniBufExplMoreThanOne=0  

let g:NERDTree_title="[NERDTree]"  
let g:winManagerWindowLayout="NERDTree|TagList"  

function! NERDTree_Start()  
    exec 'NERDTree'  
endfunction  

function! NERDTree_IsValid()  
    return 1  
endfunction  

nmap wm :WMToggle<CR>  

